REM Temporary script created is named spreport_auto
REM Used to create multiple statspack reports between two snapshots
REM Start one is taken around '07' and end one around '19'
REM Period is from the last 10 days for 9

REM Created by user PERFSTAT on localhost at 14-MAY-2020 17:36                                                                                                                                                                                                                                              
prompt Beginning statspack generation...                                                                                                                                                                                                                                                                    
set heading off feedback off lines 800 pages 5000 trimspool on trimout on                                                                                                                                                                                                                                   
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt Creating statspack report spreport_1539144224_1_0_0.txt  for instance number 1 snapshots 0 to 0                                                                                                                                                                                                      
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt                                                                                                                                                                                                                                                                                                      
Report cannot be generated because of missing data :                                                                                                                                                                                                                                                        
vdbid : 1539144224                                                                                                                                                                                                                                                                                          
vinst_num : 1                                                                                                                                                                                                                                                                                               
vstart_snap_id : 0                                                                                                                                                                                                                                                                                          
vend_snap_id : 0                                                                                                                                                                                                                                                                                            
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt Creating statspack report spreport_3861353112_1_95_101.txt  for instance number 1 snapshots 95 to 101                                                                                                                                                                                                
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt                                                                                                                                                                                                                                                                                                      
prompt Creation du statspack spreport_3861353112_1_95_101.txt                                                                                                                                                                                                                                               
define num_days = 0;                                                                                                                                                                                                                                                                                        
define begin_snap='95';                                                                                                                                                                                                                                                                                     
define end_snap='101';                                                                                                                                                                                                                                                                                      
define report_name='spreport_3861353112_1_95_101.txt ';                                                                                                                                                                                                                                                     
define dbid_force='3861353112'                                                                                                                                                                                                                                                                              
@?/rdbms/admin/spreport_param.sql                                                                                                                                                                                                                                                                           
set termout on                                                                                                                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt Creating statspack report spreport_3861353112_1_179_0.txt  for instance number 1 snapshots 179 to 0                                                                                                                                                                                                  
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt                                                                                                                                                                                                                                                                                                      
Report cannot be generated because of missing data :                                                                                                                                                                                                                                                        
vdbid : 3861353112                                                                                                                                                                                                                                                                                          
vinst_num : 1                                                                                                                                                                                                                                                                                               
vstart_snap_id : 179                                                                                                                                                                                                                                                                                        
vend_snap_id : 0                                                                                                                                                                                                                                                                                            
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt Creating statspack report spreport_3861353112_1_131_137.txt  for instance number 1 snapshots 131 to 137                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt                                                                                                                                                                                                                                                                                                      
prompt Creation du statspack spreport_3861353112_1_131_137.txt                                                                                                                                                                                                                                              
define num_days = 0;                                                                                                                                                                                                                                                                                        
define begin_snap='131';                                                                                                                                                                                                                                                                                    
define end_snap='137';                                                                                                                                                                                                                                                                                      
define report_name='spreport_3861353112_1_131_137.txt ';                                                                                                                                                                                                                                                    
define dbid_force='3861353112'                                                                                                                                                                                                                                                                              
@?/rdbms/admin/spreport_param.sql                                                                                                                                                                                                                                                                           
set termout on                                                                                                                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt Creating statspack report spreport_3861353112_1_143_149.txt  for instance number 1 snapshots 143 to 149                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt                                                                                                                                                                                                                                                                                                      
prompt Creation du statspack spreport_3861353112_1_143_149.txt                                                                                                                                                                                                                                              
define num_days = 0;                                                                                                                                                                                                                                                                                        
define begin_snap='143';                                                                                                                                                                                                                                                                                    
define end_snap='149';                                                                                                                                                                                                                                                                                      
define report_name='spreport_3861353112_1_143_149.txt ';                                                                                                                                                                                                                                                    
define dbid_force='3861353112'                                                                                                                                                                                                                                                                              
@?/rdbms/admin/spreport_param.sql                                                                                                                                                                                                                                                                           
set termout on                                                                                                                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt Creating statspack report spreport_1539144224_1_182_324.txt  for instance number 1 snapshots 182 to 324                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt                                                                                                                                                                                                                                                                                                      
prompt Creation du statspack spreport_1539144224_1_182_324.txt                                                                                                                                                                                                                                              
define num_days = 0;                                                                                                                                                                                                                                                                                        
define begin_snap='182';                                                                                                                                                                                                                                                                                    
define end_snap='324';                                                                                                                                                                                                                                                                                      
define report_name='spreport_1539144224_1_182_324.txt ';                                                                                                                                                                                                                                                    
define dbid_force='1539144224'                                                                                                                                                                                                                                                                              
@?/rdbms/admin/spreport_param.sql                                                                                                                                                                                                                                                                           
set termout on                                                                                                                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt Creating statspack report spreport_3861353112_1_167_173.txt  for instance number 1 snapshots 167 to 173                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt                                                                                                                                                                                                                                                                                                      
prompt Creation du statspack spreport_3861353112_1_167_173.txt                                                                                                                                                                                                                                              
define num_days = 0;                                                                                                                                                                                                                                                                                        
define begin_snap='167';                                                                                                                                                                                                                                                                                    
define end_snap='173';                                                                                                                                                                                                                                                                                      
define report_name='spreport_3861353112_1_167_173.txt ';                                                                                                                                                                                                                                                    
define dbid_force='3861353112'                                                                                                                                                                                                                                                                              
@?/rdbms/admin/spreport_param.sql                                                                                                                                                                                                                                                                           
set termout on                                                                                                                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt Creating statspack report spreport_3861353112_1_107_113.txt  for instance number 1 snapshots 107 to 113                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt                                                                                                                                                                                                                                                                                                      
prompt Creation du statspack spreport_3861353112_1_107_113.txt                                                                                                                                                                                                                                              
define num_days = 0;                                                                                                                                                                                                                                                                                        
define begin_snap='107';                                                                                                                                                                                                                                                                                    
define end_snap='113';                                                                                                                                                                                                                                                                                      
define report_name='spreport_3861353112_1_107_113.txt ';                                                                                                                                                                                                                                                    
define dbid_force='3861353112'                                                                                                                                                                                                                                                                              
@?/rdbms/admin/spreport_param.sql                                                                                                                                                                                                                                                                           
set termout on                                                                                                                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt Creating statspack report spreport_3861353112_1_83_89.txt  for instance number 1 snapshots 83 to 89                                                                                                                                                                                                  
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt                                                                                                                                                                                                                                                                                                      
prompt Creation du statspack spreport_3861353112_1_83_89.txt                                                                                                                                                                                                                                                
define num_days = 0;                                                                                                                                                                                                                                                                                        
define begin_snap='83';                                                                                                                                                                                                                                                                                     
define end_snap='89';                                                                                                                                                                                                                                                                                       
define report_name='spreport_3861353112_1_83_89.txt ';                                                                                                                                                                                                                                                      
define dbid_force='3861353112'                                                                                                                                                                                                                                                                              
@?/rdbms/admin/spreport_param.sql                                                                                                                                                                                                                                                                           
set termout on                                                                                                                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt Creating statspack report spreport_3861353112_1_119_125.txt  for instance number 1 snapshots 119 to 125                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt                                                                                                                                                                                                                                                                                                      
prompt Creation du statspack spreport_3861353112_1_119_125.txt                                                                                                                                                                                                                                              
define num_days = 0;                                                                                                                                                                                                                                                                                        
define begin_snap='119';                                                                                                                                                                                                                                                                                    
define end_snap='125';                                                                                                                                                                                                                                                                                      
define report_name='spreport_3861353112_1_119_125.txt ';                                                                                                                                                                                                                                                    
define dbid_force='3861353112'                                                                                                                                                                                                                                                                              
@?/rdbms/admin/spreport_param.sql                                                                                                                                                                                                                                                                           
set termout on                                                                                                                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt Creating statspack report spreport_3861353112_1_155_161.txt  for instance number 1 snapshots 155 to 161                                                                                                                                                                                              
------------------------------------------------------------------------------------------------------                                                                                                                                                                                                      
prompt                                                                                                                                                                                                                                                                                                      
prompt Creation du statspack spreport_3861353112_1_155_161.txt                                                                                                                                                                                                                                              
define num_days = 0;                                                                                                                                                                                                                                                                                        
define begin_snap='155';                                                                                                                                                                                                                                                                                    
define end_snap='161';                                                                                                                                                                                                                                                                                      
define report_name='spreport_3861353112_1_155_161.txt ';                                                                                                                                                                                                                                                    
define dbid_force='3861353112'                                                                                                                                                                                                                                                                              
@?/rdbms/admin/spreport_param.sql                                                                                                                                                                                                                                                                           
set termout on                                                                                                                                                                                                                                                                                              
set heading on feedback 6 lines 100 pages 45                                                                                                                                                                                                                                                                
prompt End of creating statspack reports                                                                                                                                                                                                                                                                    
prompt                                                                                                                                                                                                                                                                                                      
exit                                                                                                                                                                                                                                                                                                        
prompt                                                                                                                                                                                                                                                                                                      
